# Generated by Django 5.1 on 2024-09-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_sluug_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sluug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
