# Generated by Django 5.1 on 2024-09-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_sluug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sluug',
            new_name='slug',
        ),
    ]
